### ISSUE TITLE
Changed the folder for image but doesn't work

### ISSUE THREAD

**Issue by C0re-theta** [computervisiondeveloper/train-yolov8-custom-dataset-step-by-step-guide#17]
Hello, I tried to use the code for train and config on a personalized folder with apple to detect but it doesn't seems to work.
I am working on a Windows 11 computer with Visual Code Studio and I have change the path for the config to something like that:
 
path: C:\Users\ _(firstname) (lastname)_ \Desktop\test_desktop_apple\Apple_normal  # dataset root dir
train: images\train  # train images (relative to 'path')
val: images\train  # val images (relative to 'path')

with in the images/train --> the pictures of the apples and in another folder inside Apple_normal the folder labels/train --> the .txt of each picture I did with CVAT like in the tutorial.

But when I try to run it, I don't have the same thing like in the tutorial video, instead, I've got this yolo\engine\trainer:
![image](https://github.com/computervisioneng/train-yolov8-custom-dataset-step-by-step-guide/assets/170103402/1b3b53be-5b22-4063-bb10-2630cafbc28f)

What did I do wrong ? is it the name of the file folder ? does it need to be without space or in '...' ?

It can work if I am in the  C:\Users\ _(firstname) (lastname)_ \ folder but it run indefinitely and not like in the tutorial:
![image](https://github.com/computervisioneng/train-yolov8-custom-dataset-step-by-step-guide/assets/170103402/7c1543cb-1617-44a5-9063-d75c000e036a)
this appears in the Terminal with a bunch of line with this ^^^^^^^^^^^^^^ and also I have a folder named runs with detect/trainXX going from XX = 0 to 70.

**Comment by computervisioneng** [comment]
Hello, I am not sure what could be the issue, I have never encounter that error. Have you verified the path to the data and the config file are correct?

**Comment by C0re-theta** [comment]
I tried to look at the video, and I don't have that:
![image](https://github.com/computervisioneng/train-yolov8-custom-dataset-step-by-step-guide/assets/170103402/c05965ba-2491-4c9c-825e-dc3c7816f33c)
Instead I've got this
![image](https://github.com/computervisioneng/train-yolov8-custom-dataset-step-by-step-guide/assets/170103402/2873a385-5ba2-4269-abcd-161956fbe9d4)

and a lot of different line that doesn't look right...

**Comment by C0re-theta** [comment]
I've got the path like this
![image](https://github.com/computervisioneng/train-yolov8-custom-dataset-step-by-step-guide/assets/170103402/ad228de3-bb69-4040-9c7b-e6b27ee7a490)
in the folder like that:
![image](https://github.com/computervisioneng/train-yolov8-custom-dataset-step-by-step-guide/assets/170103402/5060453e-12b1-4918-bdbf-9f77c428d930)

**Comment by C0re-theta** [comment]
I really thought that the code was this simple, that I just needed to install the ultrlytics part and put in the config the path to the folder containing the train, config and folder with the pictures and txt file. But when running, I don't have the "table" that appears at the end of the tutorial.

**Comment by computervisioneng** [comment]
I am not sure what could be the issue. How many images are you using to train? If the number of images is less than the batch size, that may be throwing an error. Have you tried to train from a google colab?

**Comment by C0re-theta** [comment]
I have found a yolo file on roboflow of around 83 apple, I have reduce the size to around 16 and used CVAT to recreate the text file. I'll try with the original one if it's just a insufficient amount of picture for my issue

**Comment by C0re-theta** [comment]
I have those lines that appears in the Terminal and after that, i got a new folder in the run called trainXX and I think that if I left it running, it's going to do it until the laptop break in my mind
![image](https://github.com/computervisioneng/train-yolov8-custom-dataset-step-by-step-guide/assets/170103402/aff3cdcc-c032-4d30-8cca-f8bdf8a12897)
and I also got those and I don't think it's normal unless I did a misstep....
![image](https://github.com/computervisioneng/train-yolov8-custom-dataset-step-by-step-guide/assets/170103402/12881d4b-2d10-4edf-a8fb-0a2c0bed23cd)

Could it be possible that the name for the folder with the picture has to be unique? I tried and copy on different folder at different locations on my laptop but didn't change some of the name like the config.yaml...

**Comment by C0re-theta** [comment]
Regarding the Google Collab, I don't think I will use it because I need to have a python file on a computer. I intend of first training the model on a window computer and do something similar to the video of the tutorial on a live camera and once the code run properly, I'll have to transfer the trained program and the detection from camera on a Linux laptop.
